# Generated by Django 4.0.2 on 2022-02-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_options_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='name',
            field=models.CharField(default='f', max_length=128),
            preserve_default=False,
        ),
    ]
