# Generated by Django 4.0.2 on 2022-02-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_option_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
