# Generated by Django 4.0.2 on 2022-02-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_option_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='logo_small',
            field=models.FileField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
