# Generated by Django 4.0.2 on 2022-02-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_option_logo_small'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='helps/')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
    ]
