# Generated by Django 4.0.2 on 2022-02-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='title',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Standard Plus', 'Standard Plus'), ('Extended', 'Extended')], max_length=128),
        ),
    ]
