# Generated by Django 4.0.2 on 2022-02-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_price_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='_12_months_updates',
            new_name='twelve_months_updates',
        ),
        migrations.RemoveField(
            model_name='price',
            name='_6_months_of_support',
        ),
        migrations.AddField(
            model_name='price',
            name='six_months_of_support',
            field=models.BooleanField(default=False),
        ),
    ]
